package com.simiacryptus.cognotik.webui.servlet

import com.simiacryptus.cognotik.chat.model.ChatModel
import com.simiacryptus.cognotik.platform.ApplicationServices
import com.simiacryptus.cognotik.platform.model.Session
import com.simiacryptus.cognotik.platform.model.SessionMetadata
import com.simiacryptus.cognotik.platform.model.User
import com.simiacryptus.cognotik.platform.model.asPatch
import com.simiacryptus.cognotik.webui.application.ApplicationServer
import com.simiacryptus.cognotik.webui.servlet.handler.GitOperationHandler
import com.simiacryptus.cognotik.webui.session.SocketManager
import org.eclipse.jetty.servlet.ServletContextHandler
import org.eclipse.jetty.servlet.ServletHolder
import org.slf4j.LoggerFactory
import java.io.File
import java.util.*

/**
 *
 * To Launch:
 * Call gateway page on new session id, e.g.
 *  http://localhost:12891/health-improvement/#U-20260310-i2oc2f
 * Then open the main html page for the app, e.g.
 *  http://localhost:12891/health-improvement/fileIndex/U-20260310-i2oc2f/app.html
 * The app should load a javascript application from its relative path, which can conduct the rest of the interactions.
 * When the app needs to write files, the same path can be used with PUT requests, e.g.
 *  http://localhost:12891/health-improvement/fileIndex/U-20260310-i2oc2f/notes.md
 * When the app needs to execute DocOps renderings, it should call the servlet e.g.
 *  http://localhost:12891/docops?sessionId=U-20260310-i2oc2f&doc=ops/foo.md&target=output.md
 *
 * */
open class DocOpsApp(
    root: File,
    appId: String,
    applicationName: String = appId,
    val resourcePath : String,
    val classLoader: ClassLoader = this.javaClass.classLoader,
     val readme: String = "",
) : ApplicationServer(
  applicationName = applicationName,
  path = "/$appId",
  root = root
) {
  override val stickyInput: Boolean get() = true
  override val inputCnt get() = 0

  private val metadataStorage by lazy {
    ApplicationServices.fileApplicationServices().metadataDB
  }

  data class Settings(
      val model: ChatModel? = null,
      val fastModel: ChatModel? = null,
      val temperature: Double = 0.3,
      val budget: Double = 2.0,
      val overwriteOnRestart: Boolean = OVERWRITE,
  )

  override val settingsClass: Class<*> get() = Settings::class.java

  @Suppress("UNCHECKED_CAST")
  override fun <T : Any> initSettings(session: Session, user: User): T = Settings() as T

  fun extractResources(resourcePath: String, targetDir: File): Boolean {
    /* Single implementation, shared with the FS API 'extract-utils' action. */
    return ResourceExtractor.extract(resourcePath, targetDir, classLoader).isNotEmpty()
  }
/**
  * Writes a "self-ignoring" .gitignore into [dir]: every entry in the directory is ignored,
  * including the .gitignore file itself. Used for directories whose contents are re-extracted
  * from packaged resources on every session start and therefore should never be committed.
  */
private fun writeSelfIgnore(dir: File) {
   if (!dir.exists()) dir.mkdirs()
   File(dir, ".gitignore").writeText(
     buildString {
       appendLine("# Auto-generated by DocOpsApp - do not edit.")
       appendLine("# Contents are re-extracted from packaged resources; ignore everything here,")
       appendLine("# including this file itself.")
       appendLine("*")
     }
   )
}


  override fun newSession(user: User, session: Session): SocketManager {
    val newSession = super.newSession(user, session)!!
    val sessionRoot = newSession.resolveUserFile(".")!!
    val isExistingSession =
      sessionRoot.exists() && sessionRoot.list()?.isNotEmpty() == true && sessionRoot.listFiles()?.size!! > 2
    val currentSettings = getSettings(session, user, Settings::class.java)
    if (currentSettings == null) {
      throw IllegalStateException("Failed to load settings for session: $session")
    }
    if (isExistingSession && !currentSettings.overwriteOnRestart) {
      LoggerFactory.getLogger(DocOpsApp::class.java)
        .info("Skipping resource extraction for existing session (overwriteOnRestart=false): $session")
      return newSession
    }
    metadataStorage.updateSessionMetadata(
      user, session, SessionMetadata(
        id = session,
        name = applicationName,
        path = "/${applicationName}/fileIndex/${session.sessionId}/app.html",
        sessionTime = Date(),
        ownerId = user.id
      ).asPatch()
    )
    val extractUtil = extractResources("web/util", sessionRoot)
    if (!extractUtil) {
      throw IllegalStateException("Resource not found: web/util (classLoader=${classLoader.javaClass.name})")
    }
   /* The extracted utility bundle is regenerated per-session; keep it out of git. */
   val utilDir = File(sessionRoot, "util")
   if (utilDir.isDirectory) {
     writeSelfIgnore(utilDir)
   } else {
     LoggerFactory.getLogger(DocOpsApp::class.java)
       .warn("Expected extracted util directory not found, skipping self-ignore: ${utilDir.absolutePath}")
   }
    val extracted = extractResources(resourcePath, sessionRoot)
    if (!extracted) {
      throw IllegalStateException("Resource not found: $resourcePath (classLoader=${classLoader.javaClass.name})")
    }
    try {
      GitOperationHandler.executeCommand(sessionRoot, "git", "init")
      GitOperationHandler.executeCommand(sessionRoot, "git", "add", "-A", ".")
      GitOperationHandler.executeCommand(
        sessionRoot,
        "git",
        "commit",
        "-a",
        "-m",
        "Initial commit from DocOps app session"
      )
    } catch (e: Exception) {
      // Log but don't fail session creation if git init fails
      LoggerFactory.getLogger(DocOpsApp::class.java)
        .warn("Failed to initialize git repository for session: ${e.message}", e)
    }
    return newSession
  }


  override fun configure(webAppContext: ServletContextHandler) {
    super.configure(webAppContext)
    webAppContext.addServlet(
       ServletHolder("redirect", RouterServlet(dataStorage, applicationName)), "/*"
    )
  }




  companion object {
    val log = LoggerFactory.getLogger(DocOpsApp::class.java)
    var OVERWRITE: Boolean = false

    /** Kept for source compatibility; the implementation lives in [ResourceExtractor]. */

    fun copyFileWithLineEndingNormalization(source: File, targetFile: File) {

      ResourceExtractor.copyFileWithLineEndingNormalization(source, targetFile)
    }
  }
}