/-!
# LangSem — shared semantics prelude for the analysis engine

This is the *human-authored* Bucket A artefact (idea.md §2, §8.1). It is
never regenerated by an agent; `emit_lean.op.md` only refers to it. Emitted
`Obligations.lean` files pick a ladder rung, deep-embed the CSIR program and
state each obligation as a theorem whose hypotheses are named ledger entries.

Version: LangSem@0.1 (sketch). Bumping this version invalidates every proof
(idea.md §10.3). Extend by adding constructors, never by weakening existing
ones.
-/

namespace LangSem

/-- Semantics ladder (idea.md §8.2). Declaration order is refinement order. -/
inductive Rung where
  | ideal | bounded | trapping | memory | concurrent | deployed
  deriving DecidableEq, Repr

def Rung.level : Rung → Nat
  | .ideal      => 0
  | .bounded    => 1
  | .trapping   => 2
  | .memory     => 3
  | .concurrent => 4
  | .deployed   => 5

/-- How machine integers behave at a rung (a Bucket C idealisation knob). -/
inductive IntModel where
  | unbounded | wrapping | trapping
  deriving DecidableEq, Repr

def Rung.intModel : Rung → IntModel
  | .ideal   => .unbounded
  | .bounded => .wrapping
  | _        => .trapping

inductive Width where
  | u8 | u16 | u32 | u64 | usize
  deriving DecidableEq, Repr

/-- `usize` is modelled as 64 bits; a ledger entry must say so if it matters. -/
def Width.bits : Width → Nat
  | .u8 => 8 | .u16 => 16 | .u32 => 32 | .u64 => 64 | .usize => 64

def Width.modulus (w : Width) : Nat := 2 ^ w.bits

inductive Value where
  | int  (n : Int)
  | uN   (w : Width) (n : Nat)
  | bool (b : Bool)
  | unit
  deriving Repr

/-- Effect algebra (idea.md §5.2). -/
inductive Effect where
  | pure | alloc | read (region : String) | write (region : String)
  | diverge | panic | io | sync (order : String)
  deriving Repr

structure State where
  locals  : List (String × Value) := []
  effects : List Effect := []
  deriving Repr

inductive Outcome (σ : Type) where
  | ok      (s : σ) (v : Value)
  | panic   (s : σ) (reason : String)
  | ub      (s : σ)
  | diverge

/-- CSIR operations over already-evaluated operands (the emitter adds more). -/
inductive Op where
  | add   (w : Width) (x y : Nat)
  | sub   (w : Width) (x y : Nat)
  | div   (w : Width) (x y : Nat)
  | index (len i : Nat)
  deriving Repr

/-- Big-step evaluation of one CSIR operation at rung `S` (idea.md §8.1). -/
inductive Step (S : Rung) : State → Op → Outcome State → Prop
  | addIdeal  {σ w x y} : S.intModel = .unbounded →
      Step S σ (.add w x y) (.ok σ (.int (x + y)))
  | addWrap   {σ w x y} : S.intModel = .wrapping →
      Step S σ (.add w x y) (.ok σ (.uN w ((x + y) % w.modulus)))
  | addTrapOk {σ w x y} : S.intModel = .trapping → x + y < w.modulus →
      Step S σ (.add w x y) (.ok σ (.uN w (x + y)))
  | addTrap   {σ w x y} : S.intModel = .trapping → w.modulus ≤ x + y →
      Step S σ (.add w x y) (.panic σ "overflow")
  | subIdeal  {σ w x y} : S.intModel = .unbounded →
      Step S σ (.sub w x y) (.ok σ (.int ((x : Int) - (y : Int))))
  | subWrap   {σ w x y} : S.intModel = .wrapping →
      Step S σ (.sub w x y) (.ok σ (.uN w ((x + w.modulus - y % w.modulus) % w.modulus)))
  | subTrapOk {σ w x y} : S.intModel = .trapping → y ≤ x →
      Step S σ (.sub w x y) (.ok σ (.uN w (x - y)))
  | subTrap   {σ w x y} : S.intModel = .trapping → x < y →
      Step S σ (.sub w x y) (.panic σ "underflow")
  | divOk     {σ w x y} : y ≠ 0 →
      Step S σ (.div w x y) (.ok σ (.uN w (x / y)))
  | divZero   {σ w x} :
      Step S σ (.div w x 0) (.panic σ "division by zero")
  | indexOk   {σ len i} : i < len →
      Step S σ (.index len i) (.ok σ .unit)
  | indexOob  {σ len i} : len ≤ i →
      Step S σ (.index len i) (.panic σ "index out of bounds")

/-- Residual side conditions produced when lifting a proof one rung. -/
structure SideConditions where
  conds : List Prop

def SideConditionsHold (C : SideConditions) : Prop := ∀ c ∈ C.conds, c

/-- A deep-embedded CSIR program; the emitted file supplies the body. -/
structure Program where
  name : String
  ops  : List Op

/-- `p` never leaves the `ok` outcomes at rung `S`. -/
def NoPanic (S : Rung) (p : Program) : Prop :=
  ∀ σ op out, op ∈ p.ops → Step S σ op out → ∃ σ' v, out = .ok σ' v

/-- Refinement between rungs in its weakest useful form: `hi` panics only
    where `lo` already did. Stronger (value-preserving) variants are added
    per rung pair as the ladder is formalised (idea.md §17, Phase 3). -/
def Refines (hi lo : Rung) (p : Program) : Prop :=
  NoPanic lo p → NoPanic hi p

/-- Theorem *schema* (idea.md §8.2): the emitter computes `C` mechanically and
    proves `h` per program; the schema itself is trivial by construction. -/
theorem refine_step_schema (hi lo : Rung) (p : Program) (C : SideConditions)
    (h : SideConditionsHold C → Refines hi lo p) (hC : SideConditionsHold C) :
    Refines hi lo p := h hC

/-- Worked residual (idea.md §8.3): a trapping `u32` add is `ok` given the
    range bound that the ledger has to supply. -/
theorem add_u32_trapping_ok (x y : Nat) (σ : State) (out : Outcome State)
    (hbound : x + y < Width.u32.modulus)
    (hs : Step .trapping σ (.add .u32 x y) out) : ∃ σ' v, out = .ok σ' v := by
  cases hs with
  | addIdeal h      => exact absurd h (by decide)
  | addWrap h       => exact absurd h (by decide)
  | addTrapOk _ _   => exact ⟨_, _, rfl⟩
  | addTrap _ hge   => exact absurd hbound (Nat.not_lt.mpr hge)

end LangSem