package cognotik.actions.task

import cognotik.actions.BaseAction
import cognotik.actions.agent.toFile
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileChooser.FileChooserDescriptor
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.progress.ProgressManager
import com.intellij.openapi.progress.Task
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.DialogWrapper
import com.intellij.openapi.ui.TextFieldWithBrowseButton
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.ui.dsl.builder.Align
import com.intellij.ui.dsl.builder.panel
import com.intellij.ui.dsl.builder.selected
import com.simiacryptus.cognotik.config.AppSettingsState
import com.simiacryptus.cognotik.util.*
import com.simiacryptus.cognotik.docops.DocProcessor.Companion.newProcessor
import java.io.File
import java.util.concurrent.CompletableFuture
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import javax.swing.JComponent

/**
 * Action that creates a "permanent documentation" file for selected files/folders.
 *
 * This action:
 * 1. Collects selected files and folders from the project view
 * 2. Shows a dialog asking for the output documentation file location/name
 * 3. Creates a stub markdown file with 'documents' frontmatter entries pointing to the selected files
 * 4. Optionally runs the DocProcessor to immediately update/populate the documentation
 */
class PermdocAction : BaseAction() {
  override fun getActionUpdateThread() = ActionUpdateThread.BGT
  override fun isEnabled(event: AnActionEvent): Boolean {
    if (!super.isEnabled(event)) return false
    val selectedFiles = event.getSelectedFiles()
    return selectedFiles.isNotEmpty()
  }

  override fun handle(e: AnActionEvent) {
    val project = e.project ?: return
    val selectedFiles = e.getSelectedFiles().map { it.toFile }
    if (selectedFiles.isEmpty()) {
      UITools.showError(project, "No files or folders selected")
      return
    }
    ApplicationManager.getApplication().invokeAndWait {
      val dialog = PermdocDialog(project, selectedFiles)
      if (dialog.showAndGet()) {
        val outputFile = File(dialog.getOutputPath())
        val allFiles = collectFiles(selectedFiles)
        val outputDir = outputFile.parentFile
        outputDir.mkdirs()
        val relativePaths = allFiles.map { file ->
          val relativePath = outputDir.toPath().relativize(file.toPath()).toString().replace('\\', '/')
          relativePath
        }.sorted()
        val content = buildStubContent(relativePaths, outputFile.nameWithoutExtension)
        outputFile.writeText(content)
        LocalFileSystem.getInstance().refreshAndFindFileByIoFile(outputFile)
      }
    }
  }

  /**
   * Recursively collect all files from the given list (expanding directories).
   */
  private fun collectFiles(files: List<File>): List<File> {
    val result = mutableListOf<File>()
    for (file in files) {
      if (file.isDirectory) {
        file.walkTopDown()
          .filter { it.isFile }
          .filter { !it.name.startsWith(".") }
          .filter { !it.path.contains("/.") }
          .forEach { result.add(it) }
      } else if (file.isFile) {
        result.add(file)
      }
    }
    return result.distinct()
  }

  /**
   * Build the stub markdown documentation content with frontmatter.
   */
  private fun buildStubContent(relativePaths: List<String>, title: String): String {
    val sb = StringBuilder()
    sb.appendLine("---")
    sb.appendLine("documents:")
    for (path in relativePaths) {
      sb.appendLine("  - $path")
    }
    sb.appendLine("---")
    sb.appendLine()
    sb.appendLine("# ${title.replace('-', ' ').replace('_', ' ').replaceFirstChar { it.uppercase() }}")
    sb.appendLine()
    sb.appendLine("<!-- This documentation file was auto-generated by Permdoc. -->")
    sb.appendLine("<!-- Run the DocProcessor 'Build Related' action on this file to populate it. -->")
    sb.appendLine()
    return sb.toString()
  }


  /**
   * Dialog for configuring the Permdoc output file.
   */
  class PermdocDialog(
    project: Project,
    private val selectedFiles: List<File>
  ) : DialogWrapper(project) {
    private val outputPathField = TextFieldWithBrowseButton()

    init {
      title = "Create Permanent Documentation"
      val defaultDir =
        if (selectedFiles.first().isDirectory) selectedFiles.first() else selectedFiles.first().parentFile
      val defaultName = if (selectedFiles.size == 1) {
        val base = selectedFiles.first().let { if (it.isDirectory) it.name else it.nameWithoutExtension }
        "${base}-docs.md"
      } else {
        "documentation.md"
      }
      outputPathField.text = File(defaultDir, defaultName).absolutePath
      outputPathField.addBrowseFolderListener(
        project,
        FileChooserDescriptor(false, true, false, false, false, false).withFileFilter { it.isDirectory || it.name.endsWith(".md") },
      )
      init()
    }

    override fun createCenterPanel(): JComponent = panel {
      row("Output file:") {
        cell(outputPathField)
          .align(Align.FILL)
          .comment("Path for the new documentation markdown file")
      }
      group("Summary") {
        row {
          val fileCount = collectFileCount(selectedFiles)
          text("Selected: ${selectedFiles.size} item(s) containing $fileCount file(s)")
        }
      }
    }

    private fun collectFileCount(files: List<File>): Int {
      var count = 0
      for (file in files) {
        if (file.isDirectory) {
          count += file.walkTopDown().filter { it.isFile }.count()
        } else if (file.isFile) {
          count++
        }
      }
      return count
    }

    fun getOutputPath(): String = outputPathField.text
  }
}