/**
 * feedback.js — the fan-in channel into *Update Article*.
 *
 *   Update Article( content.md@vN, open+accepted annotations,
 *                   accepted revision items ) -> content.md@vN+1
 *
 * The docop only reads files, so the two prompt blocks are serialized into
 * `feedback.md`, which `ops/update_article_op.md` lists as a related input.
 */

import {writeFile} from '/app/fileIO.js';
import {ARTICLE_DRAFT_ID, formatRevisionRef} from './core.js';
import {annotationsToPromptBlock, isFeedable, resolveAnnotation} from './annotations.js';
import {allItems, isFeedableItem, itemsToPromptBlock, setItemStatus} from './revisions.js';

export const FEEDBACK_FILE = 'feedback.md';

const HEADER = [
    '<!-- generated by Philosophical Calculator — do not edit by hand -->',
    '# Revision feedback',
    '',
    'Apply the following reader annotations and accepted revision items to the article.',
    'Weave them in; do not append them as a list.',
    ''
];

export function collectFeedback(state, draftId = ARTICLE_DRAFT_ID) {
    const annotations = (state.annotations?.[draftId] ?? []).filter(isFeedable);
    const items = allItems(state.queues?.[draftId]).filter(isFeedableItem);
    return {annotations, items};
}

/** Writes `feedback.md`; returns what was fed so provenance can be recorded. */
export async function writeFeedbackFile(basePath, state, draftId = ARTICLE_DRAFT_ID) {
    const {annotations, items} = collectFeedback(state, draftId);
    const draft = state.drafts?.[draftId];
    const ref = draft ? formatRevisionRef({draftId, revision: draft.headRevision}) : 'unknown';

    const blocks = [
        ...HEADER,
        `_Source revision: ${ref} · ${annotations.length} annotation(s) · ${items.length} accepted item(s)._`,
        ''
    ];
    const annotationBlock = annotationsToPromptBlock(annotations);
    const itemBlock = itemsToPromptBlock(items);
    if (annotationBlock) blocks.push(annotationBlock, '');
    if (itemBlock) blocks.push(itemBlock, '');
    if (!annotationBlock && !itemBlock) {
        blocks.push('_No open annotations and no accepted revision items — treat this as a polish pass._');
    }

    await writeFile(basePath, FEEDBACK_FILE, blocks.join('\n').trimEnd() + '\n');
    return {
        annotationIds: annotations.map(a => a.id),
        itemIds: items.map(i => i.id)
    };
}

/** Flip everything that was fed to `applied`, stamped with the new revision. */
export function markFedApplied(state, fed, revision, draftId = ARTICLE_DRAFT_ID) {
    const annotationIds = new Set(fed.annotationIds);
    const itemIds = new Set(fed.itemIds);

    if (state.annotations?.[draftId]) {
        state.annotations[draftId] = state.annotations[draftId].map(a =>
            annotationIds.has(a.id)
                ? resolveAnnotation(a, 'applied', {appliedInRevision: revision})
                : a);
    }
    const queue = state.queues?.[draftId];
    if (queue) {
        state.queues[draftId] = {
            ...queue,
            batches: queue.batches.map(batch => ({
                ...batch,
                items: batch.items.map(item =>
                    itemIds.has(item.id)
                        ? setItemStatus(item, 'applied', {appliedInRevision: revision})
                        : item)
            }))
        };
    }
    return state;
}