/**
 * annotations.schema.ts
 *
 * Annotations are human (or agent) notes attached to a *specific revision* of the
 * content draft. They are the second input channel into "Update Article":
 *
 *     Update Article( draft@vN, open+accepted annotations, accepted revision items )
 *         -> draft@vN+1
 *
 * Design notes
 *  - Annotations are anchored with quote+context (see common TextAnchor) so they can
 *    survive an agentic rewrite. Re-anchoring downgrades to 'relocated' or 'orphaned'
 *    rather than deleting; orphaned annotations are surfaced in the sidebar.
 *  - Annotations are threaded: `replies` lets the user converse with an agent about a
 *    passage without polluting the top-level list.
 *  - `resolution` drives whether the annotation is fed into the next update.
 */

import { z } from 'zod';
import {
  Author,
  Confidence,
  DOCUMENT_TARGET,
  DraftRevisionRef,
  HUMAN_AUTHOR,
  Id,
  IsoDateTime,
  Markdown,
  Priority,
  SCHEMA_VERSION,
  Severity,
  Tag,
  Target,
  describeTarget,
  newId,
  nowIso,
  targetSortKey,
} from './common.schema';

/* ------------------------------------------------------------------------- *
 * Vocabulary
 * ------------------------------------------------------------------------- */

export const AnnotationKind = z.enum([
  'comment', // freeform remark
  'question', // "why does this follow?"
  'suggestion', // "consider adding X here"
  'correction', // factual/logical error to fix
  'todo', // explicit work item for the next pass
  'praise', // keep this; protects text from being rewritten away
  'flag', // needs-citation / unsupported claim / tone problem
]);
export type AnnotationKind = z.infer<typeof AnnotationKind>;

export const AnnotationResolution = z.enum([
  'open', // will be fed to the next Update Article
  'accepted', // user endorsed it; will be fed and prioritized
  'rejected', // will NOT be fed
  'applied', // folded into a revision (see appliedInRevision)
  'obsolete', // target text no longer exists / superseded
]);
export type AnnotationResolution = z.infer<typeof AnnotationResolution>;

/** Resolutions whose content should be handed to the article-update agent. */
export const FEEDABLE_RESOLUTIONS: readonly AnnotationResolution[] = ['open', 'accepted'];

/* ------------------------------------------------------------------------- *
 * Thread replies
 * ------------------------------------------------------------------------- */

export const AnnotationReply = z.object({
  id: Id,
  createdAt: IsoDateTime,
  author: Author,
  body: Markdown,
  /** Set when the reply was generated by a lens/agent rather than typed. */
  generated: z.boolean().default(false),
});
export type AnnotationReply = z.infer<typeof AnnotationReply>;

/* ------------------------------------------------------------------------- *
 * Annotation
 * ------------------------------------------------------------------------- */

export const Annotation = z.object({
  schemaVersion: z.number().int().positive().default(SCHEMA_VERSION),
  id: Id,

  /** The draft revision this annotation was authored against. */
  sourceRef: DraftRevisionRef,
  /** The latest revision the anchor was successfully resolved against. */
  resolvedAgainstRevision: z.number().int().positive().optional(),

  target: Target,
  kind: AnnotationKind.default('comment'),
  /** The annotation text itself (markdown). */
  body: Markdown,
  /**
   * Optional concrete replacement for the targeted range. When present and the
   * annotation is accepted, Update Article should prefer this text verbatim.
   */
  suggestedText: z.string().optional(),

  severity: Severity.default('minor'),
  priority: Priority.default('auto'),
  tags: z.array(Tag).default([]),

  resolution: AnnotationResolution.default('open'),
  /** Revision number in which this annotation was folded in. */
  appliedInRevision: z.number().int().positive().optional(),
  /** Why it was rejected / marked obsolete — keeps the audit trail honest. */
  resolutionNote: z.string().optional(),

  author: Author,
  createdAt: IsoDateTime,
  updatedAt: IsoDateTime,

  replies: z.array(AnnotationReply).default([]),

  /** Set when the annotation was auto-generated from a lens artifact. */
  derivedFromRevisionItemId: Id.optional(),
  /** Agent self-reported confidence, for generated annotations. */
  confidence: Confidence.optional(),

  /** UI state: collapsed pins in the gutter. */
  pinned: z.boolean().default(false),
});
export type Annotation = z.infer<typeof Annotation>;

/** All annotations for one draft, persisted as a single document. */
export const AnnotationSet = z.object({
  schemaVersion: z.number().int().positive().default(SCHEMA_VERSION),
  draftId: Id,
  updatedAt: IsoDateTime,
  annotations: z.array(Annotation).default([]),
});
export type AnnotationSet = z.infer<typeof AnnotationSet>;

/* ------------------------------------------------------------------------- *
 * Query / filter model (drives the annotations sidebar)
 * ------------------------------------------------------------------------- */

export const AnnotationQuery = z.object({
  kinds: z.array(AnnotationKind).default([]),
  resolutions: z.array(AnnotationResolution).default(['open', 'accepted']),
  severities: z.array(Severity).default([]),
  tags: z.array(Tag).default([]),
  authorKinds: z.array(z.enum(['human', 'agent', 'import', 'system'])).default([]),
  /** Free-text match against body / suggestedText / quote. */
  search: z.string().default(''),
  orphanedOnly: z.boolean().default(false),
  sortBy: z.enum(['document-order', 'created', 'updated', 'severity']).default('document-order'),
  sortDir: z.enum(['asc', 'desc']).default('asc'),
});
export type AnnotationQuery = z.infer<typeof AnnotationQuery>;

/* ------------------------------------------------------------------------- *
 * Helpers
 * ------------------------------------------------------------------------- */

export function createAnnotation(input: {
  sourceRef: DraftRevisionRef;
  body: Markdown;
  target?: Target;
  kind?: AnnotationKind;
  suggestedText?: string;
  severity?: Severity;
  tags?: Tag[];
  author?: Author;
  derivedFromRevisionItemId?: Id;
  confidence?: number;
}): Annotation {
  const ts = nowIso();
  return Annotation.parse({
    id: newId('ann'),
    sourceRef: input.sourceRef,
    resolvedAgainstRevision: input.sourceRef.revision,
    target: input.target ?? DOCUMENT_TARGET,
    kind: input.kind ?? 'comment',
    body: input.body,
    suggestedText: input.suggestedText,
    severity: input.severity ?? 'minor',
    tags: input.tags ?? [],
    author: input.author ?? HUMAN_AUTHOR,
    createdAt: ts,
    updatedAt: ts,
    derivedFromRevisionItemId: input.derivedFromRevisionItemId,
    confidence: input.confidence,
  });
}

export function isOrphaned(annotation: Annotation): boolean {
  return annotation.target.scope === 'range' && annotation.target.anchorState === 'orphaned';
}

export function isFeedable(annotation: Annotation): boolean {
  return FEEDABLE_RESOLUTIONS.includes(annotation.resolution);
}

export function isOpen(annotation: Annotation): boolean {
  return annotation.resolution === 'open' || annotation.resolution === 'accepted';
}

export function resolveAnnotation(
  annotation: Annotation,
  resolution: AnnotationResolution,
  opts: { appliedInRevision?: number; note?: string } = {},
): Annotation {
  return {
    ...annotation,
    resolution,
    appliedInRevision: opts.appliedInRevision ?? annotation.appliedInRevision,
    resolutionNote: opts.note ?? annotation.resolutionNote,
    updatedAt: nowIso(),
  };
}

export function addReply(
  annotation: Annotation,
  body: Markdown,
  author: Author = HUMAN_AUTHOR,
  generated = false,
): Annotation {
  const reply: AnnotationReply = {
    id: newId('rep'),
    createdAt: nowIso(),
    author,
    body,
    generated,
  };
  return { ...annotation, replies: [...annotation.replies, reply], updatedAt: reply.createdAt };
}

export function filterAnnotations(
  annotations: Annotation[],
  query: AnnotationQuery,
): Annotation[] {
  const q = AnnotationQuery.parse(query);
  const needle = q.search.trim().toLowerCase();

  const matched = annotations.filter((a) => {
    if (q.kinds.length && !q.kinds.includes(a.kind)) return false;
    if (q.resolutions.length && !q.resolutions.includes(a.resolution)) return false;
    if (q.severities.length && !q.severities.includes(a.severity)) return false;
    if (q.authorKinds.length && !q.authorKinds.includes(a.author.kind)) return false;
    if (q.tags.length && !q.tags.some((t) => a.tags.includes(t))) return false;
    if (q.orphanedOnly && !isOrphaned(a)) return false;
    if (needle) {
      const haystack = [
        a.body,
        a.suggestedText ?? '',
        a.target.scope === 'range' ? a.target.anchor.quote : describeTarget(a.target),
        a.tags.join(' '),
      ]
        .join('\n')
        .toLowerCase();
      if (!haystack.includes(needle)) return false;
    }
    return true;
  });

  const severityRank: Record<Severity, number> = { blocker: 0, major: 1, minor: 2, nit: 3 };
  const cmp = (a: Annotation, b: Annotation): number => {
    switch (q.sortBy) {
      case 'created':
        return a.createdAt.localeCompare(b.createdAt);
      case 'updated':
        return a.updatedAt.localeCompare(b.updatedAt);
      case 'severity':
        return severityRank[a.severity] - severityRank[b.severity];
      case 'document-order':
      default:
        return targetSortKey(a.target) - targetSortKey(b.target);
    }
  };

  matched.sort((a, b) => (q.sortDir === 'desc' ? -cmp(a, b) : cmp(a, b)));
  return matched;
}

/**
 * Deterministic serialization of annotations for the Update Article prompt.
 * Grouped by section, ordered by document position, stable across runs so that
 * identical inputs produce identical prompts (and therefore cacheable runs).
 */
export function annotationsToPromptBlock(annotations: Annotation[]): string {
  const feedable = annotations
    .filter(isFeedable)
    .sort((a, b) => targetSortKey(a.target) - targetSortKey(b.target));

  if (feedable.length === 0) return '';

  const groups = new Map<string, Annotation[]>();
  for (const a of feedable) {
    const key =
      a.target.scope === 'document'
        ? '(whole article)'
        : a.target.scope === 'section'
          ? a.target.headingPath.join(' › ')
          : a.target.anchor.headingPath.join(' › ') || '(unsectioned)';
    const bucket = groups.get(key);
    if (bucket) bucket.push(a);
    else groups.set(key, [a]);
  }

  const lines: string[] = ['## Reader annotations', ''];
  for (const [section, items] of groups) {
    lines.push(`### ${section}`, '');
    for (const a of items) {
      const flags = [a.kind, a.severity, a.resolution === 'accepted' ? 'accepted' : null]
        .filter(Boolean)
        .join(', ');
      lines.push(`- **[${flags}]** ${describeTarget(a.target)}`);
      lines.push(`  - note: ${a.body.replace(/\n+/g, ' ').trim()}`);
      if (a.suggestedText) {
        lines.push(`  - replace with: ${JSON.stringify(a.suggestedText)}`);
      }
      if (isOrphaned(a)) {
        lines.push('  - ⚠ anchor text no longer present; apply by intent, not by position');
      }
      for (const reply of a.replies) {
        lines.push(`  - reply (${reply.author.kind}): ${reply.body.replace(/\n+/g, ' ').trim()}`);
      }
    }
    lines.push('');
  }
  return lines.join('\n').trimEnd();
}

export function annotationStats(annotations: Annotation[]): {
  total: number;
  byResolution: Record<AnnotationResolution, number>;
  orphaned: number;
  feedable: number;
} {
  const byResolution = {
    open: 0,
    accepted: 0,
    rejected: 0,
    applied: 0,
    obsolete: 0,
  } as Record<AnnotationResolution, number>;

  let orphaned = 0;
  let feedable = 0;
  for (const a of annotations) {
    byResolution[a.resolution] += 1;
    if (isOrphaned(a)) orphaned += 1;
    if (isFeedable(a)) feedable += 1;
  }
  return { total: annotations.length, byResolution, orphaned, feedable };
}